const produtos = [
    { id: 1, nome: "Notebook Dell", preco: 3500, categoria: "eletrônicos", estoque: 5, desconto: 0 },
    { id: 2, nome: "Mouse Logitech", preco: 80, categoria: "eletrônicos", estoque: 15, desconto: 10 },
    { id: 3, nome: "Teclado Mecânico", preco: 350, categoria: "eletrônicos", estoque: 0, desconto: 0 },
    { id: 4, nome: "Cadeira Gamer", preco: 1200, categoria: "móveis", estoque: 8, desconto: 15 },
    { id: 5, nome: "Mesa para Computador", preco: 650, categoria: "móveis", estoque: 3, desconto: 0 },
    { id: 6, nome: "Monitor LG 24\"", preco: 800, categoria: "eletrônicos", estoque: 10, desconto: 5 },
    { id: 7, nome: "Webcam Full HD", preco: 250, categoria: "eletrônicos", estoque: 0, desconto: 0 },
    { id: 8, nome: "Headset Gamer", preco: 180, categoria: "eletrônicos", estoque: 12, desconto: 20 },
    { id: 9, nome: "SSD 480GB", preco: 280, categoria: "eletrônicos", estoque: 20, desconto: 0 },
    { id: 10, nome: "Estante para Livros", preco: 420, categoria: "móveis", estoque: 5, desconto: 10 }
];

const mediaPrecoPorCategoria = produtos => {
    const categorias = [...new Set(produtos.map(p => p.categoria))];

    console.log(categorias)

    return categorias.reduce((acumulador, categoria) => {
        const produtosCategoria = produtos.filter(p => p.categoria === categoria);
        const soma = produtosCategoria.reduce((sum, p) => + p.preco, 0)
        acumulador[categoria] = soma / produtosCategoria.lenght;
        return acumulador;
    }, {});
}

//Testes:

console.log("\n=== EXERCÍCIO 8 ===");
const medidas = mediaPrecoPorCategoria(produtos);
console.log(medidas)